# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alexa(object):
    def setupUi(self, Alexa):
        Alexa.setObjectName("Alexa")
        Alexa.resize(1041, 732)
        self.centralwidget = QtWidgets.QWidget(Alexa)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1041, 731))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 73, 220);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("alexa.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(470, 350, 111, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 670, 71, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 141, 41))
        self.textBrowser.setStyleSheet("border:none;\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(930, 20, 141, 41))
        self.textBrowser_2.setStyleSheet("border:none;\n"
"background:transparent;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.textBrowser_2.setObjectName("textBrowser_2")
        Alexa.setCentralWidget(self.centralwidget)

        self.retranslateUi(Alexa)
        QtCore.QMetaObject.connectSlotsByName(Alexa)

    def retranslateUi(self, Alexa):
        _translate = QtCore.QCoreApplication.translate
        Alexa.setWindowTitle(_translate("Alexa", "MainWindow"))
        self.pushButton.setText(_translate("Alexa", "RUN"))
        self.pushButton_2.setText(_translate("Alexa", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Alexa = QtWidgets.QMainWindow()
    ui = Ui_Alexa()
    ui.setupUi(Alexa)
    Alexa.show()
    sys.exit(app.exec_())
